### ISSUE TITLE
Add badges to launches list view

### ISSUE THREAD

**Issue by RJ-Clegg** [RocketFanOrg/RocketFanApp#102]
**Is your feature request related to a problem? Please describe.**
It would be nice to see each launch badge (if available) in the launches list view 

**Describe the solution you'd like**
Add an image next to each launch row 

**Describe alternatives you've considered**
Not having one. Which is not great.

**Additional context**
![Screenshot 2020-06-02 at 19 38 24](https://user-images.githubusercontent.com/5390694/83551658-eba4f800-a508-11ea-8e8c-41972d0de22d.png)

**Comment by squarefrog** [comment]
Agreed. What do we do if theres no badge available? 

- Show a placeholder
- Omit the Image entirely

If the new design has the badges on the right, then either option could look right.

**Comment by RJ-Clegg** [comment]
I'm not sure. I like the idea of a placeholder. For now we just won't show an image.
