### ISSUE TITLE
Add models representing the api 

### ISSUE THREAD

**Issue by RJ-Clegg** [RocketFanOrg/RocketFanApp#18]
Goals for this issue:

- [x] Add [JSON files ](https://drive.google.com/drive/folders/0B2DdgKR4GR4xdk1sRGowcUZXeE0)representing the API to `/Resources/ApiData` 

- [x]  Add Models representing the api 

- [x] Add unit tests for the models 

- [x]  Add a JSON Loader object to assist with loading JSON files 

Models should be stored in `/Models` for the time being.

**Comment by squarefrog** [comment]
Can we use `/Resources/Data`? I don't like `Api`, but I also don't like `ApiData`.

We have a couple of options here: 

- Have a seperate folder of test stubs json files, each containing one endpoint data model
- Embed the JSON directly in the model

I generally favour the latter, as seen in [this model test](https://github.com/squarefrog/sweep/blob/adb6920868d18cbc45db363a316b5715a04a8110/SweepTests/Activity/Accounts/AccountTests.swift), however some of the models in `SpaceXAPI` are fairly large.

**Comment by RJ-Clegg** [comment]
>Can we use /Resources/Data? I don't like Api, but I also don't like ApiData.

Agreed. 

As for the separate JSON files, we could do that. I wonder if it would be worth while, not checking that each field is populated during a test - perhaps, we populate an array of the test model and then simply check that it's not empty. 

Otherwise as you say, we would end up with large tests, given some of the side of the models.

**Comment by squarefrog** [comment]
The real benefit of embedding the JSON data, is that you can view the model data and test in a file, which viewing on GitHub. 

This is less of a concern in Xcode as you can load the JSON in the assistant editor.

**Comment by RJ-Clegg** [comment]
I guess we can test for actual data. If all the models are covered, we should be able to test parts of the bigger JSON responses. (As the tested objects should be under test elsewhere)
