### ISSUE TITLE
Audit Models Before Merge

### ISSUE THREAD

**Issue by squarefrog** [RocketFanOrg/RocketFanApp#21]
Before merging #20, we need to audit the models.

#### General

- [ ] Ensure acronyms are expanded, `asdsAttempts => droneLandingAttempts`
- [ ] Flatten any single use nested types into the model itself, if it makes sense.
- [ ] Revisit `Links`. Is there a better way of handling this, with maybe a key value store? For example, sometimes flickr images is an array, sometimes a single URL.

#### Units

- [ ] Make sure Unit decoding is using `decodeMassUnits` etc
- [ ] Add a comment any time Units are being used so its easier to reference later, e.g. `/// The mass units specified in kg and lb`

#### SwiftLint
- [x] Should we globally disable SwiftLints `nesting` rule?
- [ ] ~~Look at the swift lint file, do we need to allow 2 letter `identifier_name`?~~

#### Tests

- [ ] As the tests download data, we should be fetching specific id's rather than position, for example prefer `payload = payloads.first(where: { $0.id == "SES-8" })` over `payload = payloads[15]`
- [ ] Ensure optionals are tested

_TBC_

**Comment by squarefrog** [comment]
⚠️  Dragon `first_flight` optional not tested.

**Comment by squarefrog** [comment]
We have a standalone `LandingPad` structure. 

There is also a `LaunchPad` structure inside `Launches`. These pads are the same, but the `LaunchPad` has fewer properties, which would mean more optionals in `LandingPad`.

Should we stick with a simple nested `Site` struct inside `Launches` or make `LandingPad` more general?

**Comment by RJ-Clegg** [comment]
>Should we globally disable SwiftLints nesting rule?

Agreed with this - I find us manually disabling this rule more often than not. Let's also remove the comments in code were we have disabled it manually. 

>Look at the swift lint file, do we need to allow 2 letter identifier_name?

I don't think so. It needs to be the exception if two letter identifiers are used. The linter should still flag this. 

> We have a standalone `LandingPad` structure.
> 
> There is also a `LaunchPad` structure inside `Launches`. These pads are the same, but the `LaunchPad` has fewer properties, which would mean more optionals in `LandingPad`.
> 
> Should we stick with a simple nested `Site` struct inside `Launches` or make `LandingPad` more general?

I believe a `Launch Site` is very different to a `Landing Pad` and therefore we should treat them as separate.

**Comment by squarefrog** [comment]
- [x] ApiInfo
- [ ] Capsule
- [ ] Company
- [ ] Core
- [ ] Distance
- [ ] Dragon
- [ ] History
- [ ] LandingPad
- [ ] Landings
- [ ] Launch
- [ ] Links
- [ ] Location
- [ ] Mission
- [ ] MissionFragment
- [ ] Payload
- [ ] Roadster
- [ ] Rocket
- [ ] Ship
- [ ] Speed
- [ ] Units

**Comment by RJ-Clegg** [comment]
> Speed - I'm not sure we need this

I believe we do, since both `ship` and `Roadster` use it.

**Comment by squarefrog** [comment]
> I believe we do, since both `ship` and `Roadster` use it.

Sort of, ship only uses a double value for knots so that can be flattened. Roadster then only needs imperial and metric measurements which is covered by `Units`

**Comment by RJ-Clegg** [comment]
That’s a good point. We could just use Units instead...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by squarefrog** [comment]
Exactly! Could use units for roadster distance from earth/mars too.

**Comment by RJ-Clegg** [comment]
I'm not sure it will work with `Distance` to be honest. As we have two sets of units. KM and Mile - to/from distances. I think

**Comment by RJ-Clegg** [comment]
actually, we could use a `typealias' eg:

` typealias Distance = (fromEarth: Units, fromMars: Units)`

**Comment by squarefrog** [comment]
I think it would work well. So instead of 

```swift
struct Roadster {
  let distance: Distance
}

roadster.distance.fromEarthKm
roadster.distance.fromEarthMi
roadster.distance.fromMarsKm
roadster.distance.fromMarsMi
```

We would have:

```swift
struct Roadster {
  let distanceFromEarth: Units
  let distanceFromMars: Units
}

roadster.distanceFromEarth.metric
roadster.distanceFromEarth.imperial
roadster.distanceFromMars.metric
roadster.distanceFromMars.imperial
```

Doesn't reduce the length of a call, but it is more consistant with all other times we use `Units`.

**Comment by squarefrog** [comment]
> actually, we could use a typealias eg:
>
> typealias Distance = (fromEarth: Units, fromMars: Units)

That could work.. `roadster.distance.fromEarth.metric` However as its only a single use model, it would be better placed nested in roadster rather than a seperate type.
