### ISSUE TITLE
Use Navigators, Factories and DI to decouple how we show screens on the app 

### ISSUE THREAD

**Issue by RJ-Clegg** [RocketFanOrg/RocketFanApp#36]
**Proposal**

I propose we separate our logic for navigation within the app, into components that have a single 
responsibility, with the following goals in mind: 

- Clean call sites - that have no knowledge of the next VC 
- Type safe - so it is no possible to call an VC that doesn't exist or forget to pass require arguments 
- Each component should have as little knowledge of the next component it uses 
- We should be able to launch any screen, from anywhere within the app, no code duplication
- Use dependancy injection

**Implementation**

With the above in mind, actual implementation should look as close to this as possible. 

**_Protocols_**

`Navigator` - defines what a `Navigator` can do
```swift
protocol Navigator {
    associatedtype Destination

    func navigate(to destination: Destination)
}
```

`ViewController` Factory - defines how a specific VC can be constructed
```swift
protocol ViewControllerFactory {
    func makeMissionViewController(for id: Int, navigator: MissionsNavigator) -> MissionsViewController
}
```

**_Containers_**
Conforms to `ViewControllerFactory` - responsible for the building of VCs 
- We can have more than one, to limit scope if need be - as long as they conform to `ViewControllerFactory`

```swift
class DependancyContainer: ViewControllerFactory {
    func makeMissionViewController(for id: Int, navigator: MissionsNavigator) -> MissionsViewController {
        return MissionsViewController(with: id, navigator)
    }
}
```

**_Navigators_**
We can (And probably should) have multiple navigators - perhaps one per tab? 
`MissionsNavigator`'s sole job is to navigate to predefined `Destination`s

```swift
class MissionsNavigator: NSObject, Navigator {
    private var navigationController: UINavigationController?
    private let viewControllerFactory: ViewControllerFactory

    //Add more destinations here
    enum Destination {
        case mission ( _  id: Int)
    }

    init(navigationController: UINavigationController,
         viewControllerFactory: ViewControllerFactory) {
        self.navigationController = navigationController
        self.viewControllerFactory = viewControllerFactory
    }

    func navigate(to destination: Destination) {
        let viewController = makeViewController(for: destination)
        navigationController?.pushViewController(viewController, animated: true)
    }
}

private extension MissionsNavigator {
    func makeViewController(for destination: Destination) -> UIViewController {
        switch destination {
        case .mission(let missionId):
            return viewControllerFactory.makeMissionViewController(for: missionId, navigator: self)
        }
    }
}
```

**_Coordinators_**

Implementation of this would follow closely how [Paul Hudson does it in Unwrap](https://github.com/twostraws/Unwrap/blob/master/Unwrap/MainTabBarController.swift)

We would have for example a `MissionsCoordinator` that would also setup the `MissionsNavigator` for that tab - like so: 

```swift
  //setup the Navigator here - since we will have access to UINavigationController
    let navigator = MissionsNavigator(navigationController: UINavigationController(), viewControllerFactory: DependancyContainer())

    //root VC here - the only one the Coordinator needs to know about
    let mainVC = MainViewController(with: navigator)
```

**Putting it all together**

So, how do we use this and what does the call site look like? 

```swift
class MainViewController: UIViewController {
    private let navigator: MissionsNavigator

    init(with navigator: MissionsNavigator) {
        self.navigator = navigator
        super.init(nibName: nil, bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    @objc func missionDetailButtonTapped() {
        navigator.navigate(to: .mission(99)) //ID can come from the VM
    }
}
```

**Additional context**

Also, if we want a particular screen to go to a different part of the app, we can simply inject the necessary `Navigator` that knows how to go to the required screen. 

Eg injecting a `SettingsNavigator` into  `RocketsViewController` would allow it to navigate to settings, without knowing _how_ to get there. 

**Extending this a little more**

We can extend this a little more and have a `ViewModelFactory` that we would build and inject into the `ViewController` instead of actual arguments. This way, if we wanted to change what we give the `ViewModel` and inject other arguments later on, the `ViewController` has no idea this happened. 

**Alternative considerations**

I have considered Paul Hudson's implementation in the Unwrap app - however I feel the coordinators know too much and ideally, they should not be constructing VCs to present the user or even know how to do such things.

**Comment by squarefrog** [comment]
👍 I really like this approach.

**Comment by RJ-Clegg** [comment]
Closing this - will open a separate issue to have the foundation of this implemented.
