### ISSUE TITLE
Theme support abstract

### ISSUE THREAD

**Issue by squarefrog** [RocketFanOrg/RocketFanApp#43]
There should be a model which represents the current colour theme in the app. Initially this will be a dark theme, but it should be designed in a way that supports an additional Light theme later on.

I don't see a clear benefit in supporting more than a Light and Dark theme, but I'm open to suggestion. A few other apps have a Black theme which aims to reduce power consumption on OLED screens. However Black themes scroll strange due to the latency when switching on pixels.

### Implementation

I think a clean implementation of this would be a main `Theme` definition:

```swift
struct Theme {
    var accentColor: UIColor
    var toolbarColor: UIColor
    var cellTextColor: UIColor
    // and so on

    init(accentColor: String, toolbarColor: String, cellTextColor: String) {
        self.accentColor = UIColor(hexString: accentColor)
        self.toolbarColor = UIColor(hexString: toolbarColor)
        self.cellTextColor = UIColor(hexString: cellTextColor)
    }
}
```

In conjunction with extensions for the themes:

```swift
extension Theme {
    static let dark = Theme(accentColor: "#FF0000",
                            toolbarColor: "#00FF00",
                            cellTextColor: "#0000FF")
}
```

### Additional context

We will need a convenience initialise that allows passing in hex colour strings to `UIColor`.

```swift
extension UIColor {
    /// Initialise a `UIColor` from a hex string
    /// - Note: It doesn't matter if the hex string has a `#` prefix.
    /// - Parameter hexString: A 6 digit, 24-bit hex string, e.g. `#ff0000`, `#d7d7cb` etc.
    public convenience init(hexString: String) {
        let cleaned = hexString.replacingOccurrences(of: "#", with: "")

        guard cleaned.count == 6 else {
            self.init(white: 0, alpha: 1)
            return
        }

        let red, green, blue: CGFloat
        let scanner = Scanner(string: cleaned)
        var hex: UInt64 = 0

        guard scanner.scanHexInt64(&hex) else {
            self.init(white: 0, alpha: 1)
            return
        }

        red   = CGFloat((hex & 0xff0000) >> 16) / 255
        green = CGFloat((hex & 0x00ff00) >> 8) / 255
        blue  = CGFloat((hex & 0x0000ff) >> 0) / 255

        self.init(red: red, green: green, blue: blue, alpha: 1.0)
    }
}
```

### Alternatives considered

An alternative would be to mark `Theme` as decodable, and create a JSON file for theme. For example:

```json
{
  "accent_color":    "#FF0000",
  "toolbar_color":   "#00FF00",
  "cell_text_color": "#0000FF"
}
```

### Discussion

Ideally, there should be one instance of this struct, because it doesn't make sense for it to be loaded each time we use it.

Additionally, the theme could be changed at any point so it would be useful to have an accompanying protocol similar to below:

```swift
protocol Themeable {
  func apply(theme: Theme)
}
```

That way we can cascade changes down the view hierarchy.

**Comment by RJ-Clegg** [comment]
Do you think it would be worth while, having `Theme` only know about colours for things like 

- Primary 
- Secondary 
- Text 
- Secondary text
- Accent 
- Background 

Instead of being aware of a colours for things like `cellTextColor` or `toolbarColor`

**Comment by squarefrog** [comment]
Yes, but if they are too abstract it makes it too hard to figure out what colour is what.  Consider `cellTextColor` to be a name, rather than a type. The names are descriptors, not concrete types. 

The other approach is to just name the colours: `accentRed`, `darkGrey` etc. But I don’t particularly like this approach as it makes it hard to change colours down the line.

**Comment by RJ-Clegg** [comment]
That's a fair point.

**Comment by RJ-Clegg** [comment]
iOS13 now has dark mode that developers can take advantage of. With that in mind, this issue is now redundant. Closing. :)
