### ISSUE TITLE
Add launches section to the app

### ISSUE THREAD

**Issue by RJ-Clegg** [RocketFanOrg/RocketFanApp#45]
**Is your feature request related to a problem? Please describe.**
Can't view Launches 😞 

**Describe the solution you'd like**
Implement a launches screen that allows the user to do the following: 

- [x] View Past Launches 
- [x] View Upcoming Launches 
- [x] Search for a specific launch 

**Describe alternatives you've considered**
None - we need to implement this. 🚀 

**Additional context**
![all_missions](https://user-images.githubusercontent.com/5390694/56158119-78b58680-5fc1-11e9-9bc2-09dc5c90b618.png)

**Comment by squarefrog** [comment]
I see this being implemented in several stages:

- [ ] Create skeleton view controller
- [ ] Add a table view and constraints
- [ ] Cell subclass to display the data
- [ ] A table data source
- [ ] A view model to populate the cells
- [ ] Where are we going to request data? Are we going to assume this vc works only with already fetched data
- [ ] Filter by upcoming/past
- [ ] Filter by name

**Comment by RJ-Clegg** [comment]
>Add a table view and constraints

For this, I figured we could use `UITableViewController` instead - that way we don't have any setup code for the `UITableView` and no need to worry about constraints

**Comment by squarefrog** [comment]
Yeah I think this is a perfect candidate for the class.

**Comment by RJ-Clegg** [comment]
I believe we can now close this pending the following two PRs: 

- [#64](https://github.com/RocketFanOrg/RocketFanApp/pull/64)
- [#63](https://github.com/RocketFanOrg/RocketFanApp/pull/63)
