### ISSUE TITLE
Launch object no longer decodable 

### ISSUE THREAD

**Issue by RJ-Clegg** [RocketFanOrg/RocketFanApp#49]
**Describe the bug**
Some changes in the API response for `launches` has broken our decoding of the `Launch` object. 

**To Reproduce**
 Run a unit test against the latest dump of the JSON response

**Expected behavior**
For the `Launch` model to be decoded successfully 

**Additional context**

I'll update all JSON files with latest dumps and run unit tests + fix any issues that come up

**Comment by squarefrog** [comment]
Ah damn. Wondered how lo:g it’d be before this happens.
