### ISSUE TITLE
Implement API layer to expose SpaceX's API

### ISSUE THREAD

**Issue by RJ-Clegg** [RocketFanOrg/RocketFanApp#6]
Implement the API layer of the app. The goals for this are as follows: 

- Expose SpaceX's API is a robust, easy to use manner 
- We should use a `Result` type that matches Swift 5's `Result` type as closely as possible 
- End points should be in an `enum`
- Endpoints should conform at a `Endpoint` protocol
- API should take additional arguments like query params - if needed 
- Unit tests for the `routes` eg `test capsules hasUpcoming`
- Network layer - we will use `URLSession` 
- Call site should be something simple like this: 

```
API.get(.rockets) { _ in
}
```

**Comment by squarefrog** [comment]
This looks like a solid plan. Lets make the API a framework, so it is isolated from the rest of the app. 👍

**Comment by squarefrog** [comment]
The more I consider this, the less excited I am about making the actual api handler use class functions. Instead, let’s make it use instance methods, and we’ll have something hold onto the reference, likely, the coordinator.

By doing this we can expand the functionality of the handler to use operation queues. 

Consider the main coordinator loading 4 views at once. Each view wants its data fetching, as quickly as possible. We can add the requests to a concurrent queue, and ensure that the current screen is prioritised. If the user moves away from the screen we can either cancel the request or move it further down the queue. 

Additionally, this may make loading cached data easier down the road. It can certainly make testing cleaner.

By giving responsibility for owning the class to another object, we reduce the need to make it a singleton too which is another win for testing.

**Comment by squarefrog** [comment]
This is what i'm thinking for the API fetcher:

```swift
import UIKit

enum Result<Data> {
    case success(Data)
    case error(Error)
}

protocol Endpoint {
    var path: String { get }
}

enum SpaceXAPIError: Error {
    case unknownReponse
    case serverReturnedCode(Int)
    case noDataReceived
}

extension SpaceXAPIError: LocalizedError {
    var errorDescription: String? {
        switch self {
        case .unknownReponse:
            return NSLocalizedString("Server returned unknown response", comment: "Server returned unknown response")
        case .serverReturnedCode(let code):
            return NSLocalizedString("Server returned HTTP code \(code)", comment: "Server returned code")
        case .noDataReceived:
            return NSLocalizedString("No data returned by the server", comment: "Missing data error")
        }
    }
}

final class SpaceX {
    let urlSession: URLSession

    private let baseURL = URL(string: "https://api.spacexdata.com/v3")!

    init(urlSession: URLSession) {
        self.urlSession = urlSession
    }

    func get(_ endpoint: Endpoint, completion: @escaping (Result<Data>) -> Void) -> URLSessionTask {
        let url = baseURL.appendingPathComponent(endpoint.path)
        let task = urlSession.dataTask(with: url) { data, urlResponse, error in
            // If there is an error, return it
            if let error = error {
                completion(Result.error(error))
                return
            }

            guard let httpResponse = urlResponse as? HTTPURLResponse else {
                completion(Result.error(SpaceXAPIError.unknownReponse))
                return
            }

            // Check HTTP code is in the acceptable range
            guard (200 ..< 300).contains(httpResponse.statusCode) else {
                completion(Result.error(SpaceXAPIError.serverReturnedCode(httpResponse.statusCode)))
                return
            }

            // Check we have data
            guard let data = data else {
                completion(Result.error(SpaceXAPIError.noDataReceived))
                return
            }

            completion(Result.success(data))
        }

        task.resume()

        return task
    }
}

```

**Comment by squarefrog** [comment]
Updated with optional parameters

**Comment by RJ-Clegg** [comment]
Looks good to me 

If this a final draft, I’d remove the comments by the guard statements as well as `import UIKit` at the top as its not used (As far as I can see)

**Comment by squarefrog** [comment]
Its current in my playground scratch pad, which is why it has the import, and `Result`, `Endpoint` etc definitions. 

With regard to comments, do you favour no comments at all?

**Comment by RJ-Clegg** [comment]
> With regard to comments, do you favour no comments at all?

I think comments should tell us _why_ we are doing something rather than _what._ The _what_ should be clear when reading the code (Which is true for this case)

**Comment by RJ-Clegg** [comment]
To add, we should only comment on the code if its not clear why we are doing a certain thing.

**Comment by squarefrog** [comment]
OK that sounds fair
