### ISSUE TITLE
Sort Launches in descending order 

### ISSUE THREAD

**Issue by RJ-Clegg** [RocketFanOrg/RocketFanApp#65]
**Is your feature request related to a problem? Please describe.**

It would be good to have the launches, sorted by defending order based on launch dates 
For past launches, the most recent launch that took place and for upcoming launches, the very next launch. 

**Describe the solution you'd like**
Launches to be in defending order.

**Comment by squarefrog** [comment]
So would this be DESCENDING by launch date for past launches, and ASCENDING for future dates?

**Comment by RJ-Clegg** [comment]
>So would this be DESCENDING by launch date for past launches, and ASCENDING for future dates?

Yes, I think that makes the most sense?

**Comment by squarefrog** [comment]
Yes absolutely
