### ISSUE TITLE
Update the app to support iOS 13 and newer only

### ISSUE THREAD

**Issue by RJ-Clegg** [RocketFanOrg/RocketFanApp#68]
With all the cool, shiny new APIs from Apple only supporting iOS13 and newer; we should update the app to take advantage of these shiny new things. 🚀

**Comment by squarefrog** [comment]
⚠️ Bleeding edge!!! ⚠️ 

I think this makes sense. It's a passion project, no business requirement to support older version.

Also bitrise has an Xcode 11 stack ready..

**Comment by RJ-Clegg** [comment]
>Also bitrise has an Xcode 11 stack ready..

Good point; we will need to change the stack for future builds.
