### ISSUE TITLE
About/Settings screen

### ISSUE THREAD

**Issue by squarefrog** [RocketFanOrg/RocketFanApp#88]
This tab should include a couple of overridable settings, and show company/api info.

**Note** should we still have a dark mode switch?

Related to #35.

![Settings](https://user-images.githubusercontent.com/343450/64607162-dce94480-d3bf-11e9-8e02-580c0a4b2923.png)

**Comment by RJ-Clegg** [comment]
With regards to the dark mode switch, I think we should follow Apple's approach on this and leave it up to the system to decide on app theme.

**Comment by squarefrog** [comment]
Works for me.
